default:
  shortname: family_letters
  collection_desc: Family Letters
  es_type: family_letters

  variables_html:
    image_large: 800
    image_thumb: 150

# development:
  # development overrides here
# production:
  # production overrides here
