default:
  collection: family_letters
  collection_desc: Family Letters
  data_base: https://cdrhmedia.unl.edu
  media_base: https://cdrhmedia.unl.edu
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
threads: 20
development:
  data_base: https://cdrhdev1.unl.edu/media
  es_path: https://cdrhdev1.unl.edu/elastic
  es_index: cdrhapidev-v1
  site_url: https://cdrhdev1.unl.edu/family_letters
production:
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v1
