default:
  collection: family_letters
  collection_desc: Family Letters
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  media_base: https://cdrhmedia.unl.edu/iiif/2/family_letters%2F

# development:
  # development overrides here
# production:
  # production overrides here
