default:
  collection: family_letters
  collection_desc: Family Letters
  data_base: https://cdrhmedia.unl.edu
  media_base: https://cdrhmedia.unl.edu
  tei_html_xsl: scripts/overrides/tei_to_html.xsl
  threads: 20
  # scrape_endpoint is tacked onto the end of site_url
  scrape_endpoint: content_pages
  scrape_website: true
  # download location-centric API results which will later
  # for use with the api_json format to create geoJSON
  api_request: true
  api_endpoint: https://cdrhapi.unl.edu/v2/collection/family_letters/items
  api_version: "2.0"
development:
  data_base: https://servername.unl.edu/media
  es_path: https://servername.unl.edu/elastic
  es_index: cdrhapidev-v2
  site_url: https://servername.unl.edu/family_letters
  api_endpoint: https://servername.unl.edu/api/v2/collection/family_letters/items
production:
  es_path: https://cdrhapi.unl.edu/elastic
  es_index: cdrhapi-v2
  site_url: https://familyletters.unl.edu
  scrape_website: false
