default:
  shortname: family_letters
  collection: family_letters
  collection_desc: Family Letters
  site_url: https://cdrhdev1.unl.edu/family_letters
  tei_html_xsl: collections/family_letters/scripts/tei.p5.xsl
  media_base: https://cdrhmedia.unl.edu

  variables_html:
    image_large: 800
    image_thumb: 150

# development:
  # development overrides here
# production:
  # production overrides here
